TASK: "CatRelDet"
MODEL:
  WEIGHT: "outputs/objdet/model_8e.pth"
  NUM_OBJ_CLASSES: 100
  NUM_PRED_CLASSES: 69
  NEG2POS: 3
  NUM_PRED_SAMPLES: 30
  NUM_DETECTIONS: 15
  HIDDEN_CHANNELS: 768
DATASETS:
  TRAIN: ("vr_train",)
  TEST: ("vr_test",)
SOLVER:
  BATCH_SIZE: 32
  LR: 0.1
  GAMMA: 0.1
  MILESTONES: (4, 5)
  MAX_EPOCH: 6
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 32
