TASK: "CatRelDet"
MODEL:
  WEIGHT: "outputs/objdet_best/model_8e.pth"
  NUM_OBJ_CLASSES: 100
  NUM_PRED_CLASSES: 69
  IOU_FLOOR: 0.5
  N2P: 1
  HIDDEN_CHANNELS: 768
  DETECTOR:
    SCORE_THRESH: 0.01
    NUM_DETECTIONS: 15
DATASETS:
  TRAIN: ("vr_train",)
  TEST: ("vr_test",)
SOLVER:
  BATCH_SIZE: 36
  LR: 0.1
  GAMMA: 0.1
  MILESTONES: (4, 7)
  MAX_EPOCH: 8
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 32
