TASK: "ObjCls"
MODEL:
  NUM_CLASSES: 100
  BACKBONE:
    ARCHITECTURE: "vgg16_bn"
DATASETS:
  TRAIN: ("vrs_train",)
  TEST: ("vrs_test",)
INPUT:
  SIZE: (224, 224)
SOLVER:
  BATCH_SIZE: 32
  LR: 0.01
  GAMMA: 0.1
  MILESTONES: (3, 5)
  MAX_EPOCH: 6
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 16
