TASKS: ("OBJCLS", )
MODEL:
  WEIGHT: ""
  NUM_CLASSES: 100
  BACKBONE:
    ARCHITECTURE: "vgg16_bn"
DATASETS:
  TRAIN: ("vrs_train",)
  TEST: ("vrs_test",)
INPUT:
  SIZE: (224, 224)
SOLVER:
  BATCH_SIZE: 8
  LR: 0.005
  GAMMA: 0.1
  MILESTONES: (6, )
  MAX_EPOCH: 8
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 16
