TASK: "PredDet"
MODEL:
  WEIGHTS: ("outputs/objcls_best/model_8e.pth","outputs/predcls_best/model_8e.pth")
  NUM_OBJ_CLASSES: 100
  NUM_PRED_CLASSES: 46
  BACKBONE:
    ARCHITECTURE: "vgg16"
DATASETS:
  TRAIN: ("vrs_train",)
  TEST: ("vrs_test",)
INPUT:
  SIZE: (224, 224)
SOLVER:
  BATCH_SIZE: 32
  LR: 0.0005
  GAMMA: 0.1
  MILESTONES: (4, 7)
  MAX_EPOCH: 8
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
TEST:
  BATCH_SIZE: 64
